name: CI/CD

on:
  push:
    branches: ["*"]
  workflow_dispatch:

env:
  SERVICENOW_INSTANCE_URL: https://dev148429.service-now.com

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v3.6.0
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test src/*.spec.ts

  deploy:
    needs: [test]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-22.04
    env:
      SERVICENOW_USERNAME: ${{ secrets.SERVICENOW_USERNAME }}
      SERVICENOW_PASSWORD: ${{ secrets.SERVICENOW_PASSWORD }}
    steps:
      - name: Setup latest Alpine Linux
        uses: jirutka/setup-alpine@v1
      - run: apk update && apk add secret-service nodejs
        shell: alpine.sh --root {0}
      - name: Install the ServiceNow SDK
        run: npm install -g @servicenow/sdk
        shell: alpine.sh {0}
      - name: Install dependencies
        run: npm install
        shell: alpine.sh {0}
      - name: Save authentication Profile
        run: npm run now-login
        shell: alpine.sh {0}
      - name: Fetch metadata
        run: now-sdk fetch
        shell: alpine.sh {0}
      - name: Deploy
        run: npm run build && npm run deploy
        shell: alpine.sh {0}
